main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.tambah, name='tambah'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('jadwal/<int:id>/', views.description, name='deskripsi'),
    path('jadwal/<int:id>/delete/', views.delete, name='delete'),
    path('tambah/', views.form, name='tambah'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

class Matkul(models.Model):
    matkul_name = models.CharField(max_length = 200)
    dosen_name = models.CharField(max_length = 200)
    jumlah_sks = models.IntegerField()
    deskripsi = models.TextField()
    tahun_semester = models.CharField(max_length = 200)
    ruang_kelas = models.CharField(max_length = 200)

main/forms.py
from django import forms
from .models import Matkul

##Create your forms here

class inputform(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = '__all__'
        

main/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .models import Matkul
from .forms import inputform


def tambah(request):
    form = inputform()
    return render(request, 'main/add.html', {'form' : form})

def jadwal(request):
    matkuls = Matkul.objects.all()
    context = {
        'matkul' : matkuls
    }
    return render(request, 'main/result.html', context)

def form(request):
    form = inputform(request.POST or None)
    if(form.is_valid() and request.method == "POST"):
        form.save()
        return  HttpResponseRedirect('/jadwal')
    else:
        return HttpResponseRedirect('/')

def description(request, id):
    try:
        matkuls = Matkul.objects.get(id=id)
        context = {
            'matkul' : matkuls
            }
        return render(request,'main/detail.html', context)
    except Exception:
        return HttpResponseRedirect('/jadwal')

def delete(request, id):
    try:
        Matkul.objects.get(id=id).delete()
        return HttpResponseRedirect('/jadwal')
    except Exception:
        return HttpResponseRedirect('/jadwal')

main/templates/main/add.html
<!DOCTYPE html>
{% extends 'base.html' %}


{% block content %}
    <form action="/tambah/" method="POST" style=";">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
<input type="submit" value="Submit" style="font-size: large; font-weight: bold;">
</form>

{% endblock content %}

main/templates/main/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="yes">
            <table>
                <tr>
                    <th>Mata Kuliah</th>
                    <th>Dosen Pengajar</th>
                    <th>Jumlah SKS</th>
                    <th>Deskripsi</th>
                    <th>Semester</th>
                    <th>Ruang Kelas</th>
                </tr>
                <tr>
                    <td>{{matkul.matkul_name}}</td>
                    <td>{{matkul.dosen_name}}</td>
                    <td>{{matkul.jumlah_sks}}</td>
                    <td>{{matkul.deskripsi}}</td>
                    <td>{{matkul.tahun_semester}}</td>
                    <td>{{matkul.ruang_kelas}}</td>
                <tr>
                    <td><a href="delete">Delete</a></td>
                </tr>
            </table>
        </div>

{% endblock content %}

main/templates/main/result.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
    {% if matkul %}
    <div class="yes">
    <table>
        <tr>
            <th>Mata Kuliah</th>
            <th>Dosen Pengajar</th>
        </tr>
        {% for form in matkul %}
        <tr>
            <td>{{form.matkul_name}}</td>
            <td>{{form.dosen_name}}</td>
            <td><a href="{{form.id}}">Detail</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
    {% endif %}

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
 <head>
  {% include 'navbar.html'%}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block meta %}
    {% endblock meta %}
  </head>
  <body>
   
      {% block content %}
      {% endblock content %}

  
  </body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
    <nav>
        <ul>
            <li><a href="{% url 'main:tambah'%}">Form Matkul</a></li>
            <li><a href="{% url 'main:jadwal'%}">Daftar</a></li>
        </ul>
    </nav>
</html>